#sudo: required
dist: trusty # Ubuntu 14.04 LTS
language: python
matrix:
 include:
#  - python: "2.6"
  - python: "2.7"
#  - python: "3.2"
#  - python: "3.3"
  - python: "3.5"
#  - python: "3.6-dev"
#  - python: "nightly"
 allow_failures:
  - python: "3.5"
#  - python: "3.6-dev"
#  - python: "nightly"
install: true # no installation
#install: python setup.py install
#install: "pip install -r requirements.txt"
#script: pytest # or py.test for Python versions 3.5 and below
#script: if [[ $TRAVIS_PYTHON_VERSION > 3.5 ]]; then pytest; else py.test; fi
#script: pytest
#script: echo foo # avoid any tests
script: nosetests
after_success:
 - python QuadraticEquation.py 2,10,1
notifications:
 email:
  recipients:
   - tomek.jelinski@gmail.com
   - tomasz.jelinski@us.edu.pl
  on_success: never # or always or change
  on_failure: never # or always or change
