#sudo: required
dist: trusty
#dist: xenial
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
#  - "nightly"
# install: true # no installation
#install: python setup.py install
#install: "pip install -r requirements.txt"
#script: pytest # or py.test for Python versions 3.5 and below
script: echo foo # avoid any tests
notifications:
 email:
  recipients:
   - tomek.jelinski@gmail.com
   - tjel@fuw.edu.pl
  on_success: change
  on_failure: always
