#sudo: required
#dist: trusty
dist: xenial
language: python
matrix:
 include:
  - python: "2.6"
  - python: "2.7"
  - python: "3.2"
  - python: "3.3"
  - python: "3.6"
#  - python: "nightly"
# allow_failures:
#  - python: "nightly"
  
install: true # no installation
#install: python setup.py install
#install: "pip install -r requirements.txt"
#script: pytest # or py.test for Python versions 3.5 and below
script: if [[ $TRAVIS_PYTHON_VERSION > 3.5 ]]; then pytest; else py.test; fi
#script: echo foo # avoid any tests
notifications:
 email:
  recipients:
   - tomek.jelinski@gmail.com
   - tomasz.jelinski@us.edu.pl
  on_success: never # or always or change
  on_failure: never # or always or change
