sudo: required
dist: trusty
#dist: xenial
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
#  - "nightly"
install: true
#install: python setup.py install
#script: echo foo
script: py.test
notifications:
 email:
  recipients:
   - tomek.jelinski@gmail.com
   - tjel@fuw.edu.pl
  on_success: change
  on_failure: always
